# a cordis harvest, java soilwise_doi.jar, DBWrite.main()
default:
  interruptible: false
stages:
  - run-harvest
  
# metadata
harvest-cordis-turtle-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/eclipse-temurin:17-alpine
  stage: run-harvest
  script:
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USERNAME=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST

    - mkdir /opt/app
    - cp cordis/soilwise_doi.jar /opt/app
#    - java -jar /opt/app/soilwise_doi.jar impact4soil
    - java -jar /opt/app/soilwise_doi.jar turtle
  rules:  
    - if: $PROJECT != "cordis"
      when: never
    - if: $CI_COMMIT_BRANCH == "dev"


# metadata
harvest-cordis-turtle-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/eclipse-temurin:17-alpine
  stage: run-harvest
  script:
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USERNAME=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    
    - mkdir /opt/app
    - cp cordis/soilwise_doi.jar /opt/app
    - java -jar /opt/app/soilwise_doi.jar doi
    - java -jar /opt/app/soilwise_doi.jar title
    - java -jar /opt/app/soilwise_doi.jar turtle
  rules:  
    - if: $PROJECT != "cordis"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
