# a inspire harvest, db credentials are populated with git ci variables
default:
  interruptible: false
stages:
  - run-harvest
  
# metadata
harvest-he-projects-openaire-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_LABEL=OPENAIRE 

    - pip3 install -r soilmission/requirements.txt
    - python3 soilmission/metadata.py
  rules:  
    - if: $PROJECT != "HE-PROJECTS-OPENAIRE"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"

# metadata
harvest-he-projects-openaire-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_LABEL=OPENAIRE 

    - pip3 install -r soilmission/requirements.txt
    - python3 soilmission/metadata.py
  rules:  
    - if: $PROJECT != "HE-PROJECTS-OPENAIRE"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"