# a inspire harvest, db credentials are populated with git ci variables
default:
  interruptible: false
stages:
  - run-harvest

# metadata
harvest-inspire-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_URL=https://inspire-geoportal.ec.europa.eu/srv/eng/csw
    - export HARVEST_FILTER=[{"keyword":"soil"}]    
    - export HARVEST_LABEL=INSPIRE 

    - pip3 install -r csw/requirements.txt
    - python3 csw/metadata.py
  rules:  
    - if: $PROJECT != "INSPIRE"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"


# metadata
harvest-inspire-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_URL=https://inspire-geoportal.ec.europa.eu/srv/eng/csw
    - export HARVEST_FILTER=[{"th_httpinspireeceuropaeutheme-theme.link":"http://inspire.ec.europa.eu/theme/so"}]
    - export HARVEST_LABEL=INSPIRE 

    - pip3 install -r csw/requirements.txt
    - python3 csw/metadata.py
  rules:  
    - if: $PROJECT != "INSPIRE"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
