# query openaire to enrich DOIs, java soilwise_doi.jar, DBWrite.main()
default:
  interruptible: false
stages:
  - run-harvest
  
# metadata
harvest-openaire-turtle-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/eclipse-temurin:17-alpine
  stage: run-harvest
  script:
    - export POSTGRES_DB=$POSTGRES_JDBC_TEST
    - export POSTGRES_USERNAME=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST

    - mkdir /opt/app
    - cp cordis/soilwise_doi.jar /opt/app
    - java -jar /opt/app/soilwise_doi.jar openairedoi
    - java -jar /opt/app/soilwise_doi.jar turtle
  rules:  
    - if: $PROJECT != "openaire"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"


# metadata
harvest-openaire-turtle-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/eclipse-temurin:17-alpine
  stage: run-harvest
  script:
    - export POSTGRES_DB=$POSTGRES_JDBC_PROD
    - export POSTGRES_USERNAME=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    
    - mkdir /opt/app
    - cp cordis/soilwise_doi.jar /opt/app
    - java -jar /opt/app/soilwise_doi.jar openairedoi
    - java -jar /opt/app/soilwise_doi.jar turtle
  rules:  
    - if: $PROJECT != "openaire"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
