# a inspire harvest, db credentials are populated with git ci variables
default:
  interruptible: false
stages:
  - run-harvest

# metadata
harvest-record-to-pycsw-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/geopython/pycsw@sha256:2b90752b8d53838390c49d4bfef633d1e7c667f9031efa56faaae4552e6d548b
  stage: run-harvest 
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - pip3 install -r record-to-pycsw/requirements.txt
    - python3 record-to-pycsw/metadata.py
  rules:  
    - if: $PROJECT != "RECORD2PYCSW"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"

# metadata
harvest-record-to-pycsw-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/geopython/pycsw@sha256:2b90752b8d53838390c49d4bfef633d1e7c667f9031efa56faaae4552e6d548b
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - pip3 install -r record-to-pycsw/requirements.txt
    - python3 record-to-pycsw/metadata.py
  rules:  
    - if: $PROJECT != "RECORD2PYCSW"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"