# a inspire harvest, db credentials are populated with git ci variables
default:
  interruptible: false
stages:
  - run-harvest
  
# metadata | this won't work, because endpoint is not open to outside
harvest-translation-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.18-slim-bookworm
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export TR_CALLBACK_URL=https://api.soilwise-he.containers.wur.nl/tolk/callback
    - export TR_LOGIN=$EC_TRANS_LOGIN
    - export TR_PASSCODE=$EC_TRANS_PASSCODE
  
    # - pip3 install -r translate/requirements.txt
    # - python3 translate/request-translation.py
  rules:  
    - if: $PROJECT != "TRANSLATION"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"


# metadata
harvest-translation-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.18-slim-bookworm
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export TR_CALLBACK_URL=https://api.soilwise-he.containers.wur.nl/tolk/callback
    - export TR_LOGIN=$EC_TRANS_LOGIN
    - export TR_PASSCODE=$EC_TRANS_PASSCODE
    
    - pip3 install -r translate/requirements.txt
    - python3 translate/extract-translation.py
    - python3 translate/request-translation.py
  rules:  
    - if: $PROJECT != "TRANSLATION"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
