# a inspire harvest, db credentials are populated with git ci variables
default:
  interruptible: false
stages:
  - run-harvest

# metadata
run-harvest-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/pvgenuchten/geodatacrawler:1.5.4
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_URL=$HARVEST_URL_TEST

    - pip3 install -r ../inspire/requirements.txt
    - python3 ../inspire/metdata.py
  only:
    - dev

# metadata
run-harvest-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/pvgenuchten/geodatacrawler:1.5.4
  stage: run-harvest
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    - export HARVEST_URL=$HARVEST_URL_TEST

    - pip3 install -r ../inspire/requirements.txt
    - python3 ../inspire/metdata.py
  only:
    - main